#pragma once

#define DFR_DEVICE_REQUEST_HEADER 0x15120002
#define DFR_DEVICE_RESPONSE_HEADER 0x01140000

#define DFR_DEVICE_UPDATE_FB_REQUEST_HEADER 0x00120002
#define DFR_DEVICE_UPDATE_FB_REQUEST_RSVD_VALUE_1 0x00000009

#define DFR_GENERIC_REQUEST_END 0x00000010

#define DFR_GET_INFO_KEY 0x47494e46 // GINF
#define DFR_HOST_READY_KEY 0x52454459 // REDY
#define DFR_CLEAR_SCREEN_KEY 0x434c4452 // CLDR

#define DFR_FRAMEBUFFER_FORMAT 0x52474241 // ABGR, Actually Alpha does not transmit
#define DFR_FRAMEBUFFER_PIXEL_BYTES 3

#define DFR_INIT_GINF_RETRY_MAX 100

#pragma pack(push)
#pragma pack(1)
typedef struct _DFR_GENERIC_REQUEST_HEADER {
	UINT32 RequestHeader;
	UINT32 Reserved1;
	UINT32 Reserved2;
	UINT32 RequestLength;
} DFR_GENERIC_REQUEST_HEADER, *PDFR_GENERIC_REQUEST_HEADER;

typedef struct _DFR_GENERIC_REQUEST_CONTENT {
	UINT32 RequestKey;
	UCHAR Reserved[8];
	UINT32 End;
} DFR_GENERIC_REQUEST_CONTENT, *PDFR_GENERIC_REQUEST_CONTENT;

typedef struct _DFR_GENERIC_REQUEST {
	DFR_GENERIC_REQUEST_HEADER Header;
	DFR_GENERIC_REQUEST_CONTENT Content;
} DFR_GENERIC_REQUEST, *PDFR_GENERIC_REQUEST;

typedef struct _DFR_UPDATE_FB_REQUEST_CONTENT {
	UINT32 FrameId;
	UINT32 Reserved1;
	UCHAR Reserved2[24];
	UINT16 BeginX;
	UINT16 BeginY;
	UINT16 Width;
	UINT16 Height;
	UINT32 BufferSize;
} DFR_UPDATE_FB_REQUEST_CONTENT, *PDFR_UPDATE_FB_REQUEST_CONTENT;

typedef struct _DFR_UPDATE_FB_REQUEST {
	DFR_GENERIC_REQUEST_HEADER Header;
	DFR_UPDATE_FB_REQUEST_CONTENT Content;
} DFR_UPDATE_FB_REQUEST, *PDFR_UPDATE_FB_REQUEST;

typedef struct _DFR_INFORMATION_RESPONSE {
	UINT32 ResponseHeader;
	UINT32 Reserved1;
	UINT64 Reserved2;
	UINT32 ResponseMessageKey;
	UINT32 Reserved3;
	UINT32 Reserved4;
	UINT32 Reversion;
	UINT32 Width;
	UINT32 Height;
	UCHAR  Reserved5[13];
	UINT32 PixelFormat;
	UCHAR  Reserved6[8];
} DFR_INFORMATION, *PDFR_INFORMATION;
#pragma pack(pop)
