#pragma once

// DFR device type
#define FILE_DEVICE_DFR 0x8086

// DFR IO functions
#define FUNCTION_UPDATE_FRAMEBUFFER 0x801
#define FUNCTION_CLEAR_FRAMEBUFFER 0x802

// DFR Host IOCTLs
#define IOCTL_DFR_UPDATE_FRAMEBUFFER CTL_CODE(FILE_DEVICE_DFR, \
	FUNCTION_UPDATE_FRAMEBUFFER, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_DFR_CLEAR_FRAMEBUFFER CTL_CODE(FILE_DEVICE_DFR, \
	FUNCTION_CLEAR_FRAMEBUFFER, METHOD_BUFFERED, FILE_WRITE_DATA)

// Apple DFR IOCTLs
#define IOCTL_DFR_KBD_FN_PRESSED 0xb4042404
#define IOCTL_DFR_KBD_FN_RELEASED 0xb4042408

#pragma pack(push)
#pragma pack(1)
typedef struct _DFR_HOSTIO_UPDATE_FRAMEBUFFER_HEADER {
	UINT16 BeginX;
	UINT16 BeginY;
	UINT16 Width;
	UINT16 Height;
	UINT32 FrameBufferPixelFormat;
	UINT32 RequireVertFlip;
} DFR_HOSTIO_UPDATE_FRAMEBUFFER_HEADER, *PDFR_HOSTIO_UPDATE_FRAMEBUFFER_HEADER;
#pragma pack(pop)
