#pragma once

// DFR device type
#define FILE_DEVICE_DFR 0x8086

// DFR IO functions
#define FUNCTION_UPDATE_FRAMEBUFFER 0x801

// DFR Host IOCTLs
#define IOCTL_DFR_UPDATE_FRAMEBUFFER CTL_CODE(FILE_DEVICE_DFR, FUNCTION_UPDATE_FRAMEBUFFER, METHOD_BUFFERED, FILE_WRITE_DATA)

